<?php

require_once 'functions.php';

/**
 *  Implements hook_help.
 *  
 *  Displays help and module information.
 *  
 *  @param path  Which path of the site we're using to display help
 *  @param arg   Array that holds the current path as returned from arg() function
 */
function onelogin_saml_help($path, $arg) {
  switch ($path) {
    case "admin/help#onelogin_saml":
      return '<p>'.  t("Allows Drupal to function as a SAML Service Provider. This means that users can authenticate to Drupal (without a username or password) via OneLogin or other SAML IDP (Identity Provider)") .'</p>';
      break;
   }
}

/**
 * Implements hook_menu()
 */
function onelogin_saml_menu(){
  $items = array();

  $items['admin/config/onelogin_saml'] = array(
    'title' => 'Configure OneLogin SAML',
    'description' => 'Configuration of OneLogin SAML',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('onelogin_saml_form'),
    'access arguments' => array('config saml'),
    'weight' => -10,
    'file' => 'onelogin_saml.admin.inc',
  );

  $items['onelogin_saml/sso'] = array(
    'title' => 'SAML SP-Iniiated SSO',
    'page callback' => 'onelogin_saml_sso',
    'access callback' => array(1),
    'type' => MENU_CALLBACK
  );

  $items['onelogin_saml/acs'] = array(
    'title' => 'SAML Assertion Consumer Service',
    'page callback' => 'onelogin_saml_acs',
    'access callback' => array(1),
    'type' => MENU_CALLBACK
  );

  $items['onelogin_saml/sls'] = array(
    'title' => 'SAML Service Logout Service',
    'page callback' => 'onelogin_saml_sls',
    'access callback' => array(1),
    'type' => MENU_CALLBACK
  );

  $items['onelogin_saml/metadata'] = array(
    'title' => 'SAML SP Metadata',
    'page callback' => 'onelogin_saml_metadata',
    'access callback' => array(1),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * * Implements hook_permission()
 *  */
function onelogin_saml_permission(){
  return array(
    'config saml' => array(
      'title' => t('Configure SAML Authentication'),
      'restricted' => true
    )
  );
}

/**
 * Implements hook_user_logout().
 */
function onelogin_saml_user_logout($account) {
  $enable_slo = variable_get('saml_options_slo', FALSE);
  $made_sso_login = isset($_COOKIE['drupal_saml_login']) && $_COOKIE['drupal_saml_login'];
  if ($enable_slo && $made_sso_login) {
    onelogin_saml_slo();
  }
  else if ($made_sso_login) {
    setcookie('drupal_saml_login', 0, time() + 3600);
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function onelogin_saml_form_user_login_block_alter(&$form, &$form_state) {
  _onelogin_saml_user_login_form_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function onelogin_saml_form_user_login_alter(&$form, &$form_state) {
  _openid_user_login_form_alter($form, $form_state);
}

function _onelogin_saml_user_login_form_alter(&$form, &$form_state) {
  $showSamlLink = variable_get('saml_options_saml_link', FALSE);

  if ($showSamlLink) {
    // Add a "Log in using SAML" link to the user-login form.
    $items = array();
    $items[] = array(
      'data' => l(t('Log in using SAML'), url('onelogin_saml/sso', array('relative' => TRUE)), array('external' => TRUE)), 
      'class' => array('saml-link'),
    );

    $form['onelogin_saml_login_links'] = array(
      '#theme' => 'item_list', 
      '#items' => $items, 
      '#attributes' => array('class' => array('onelogin_saml_login-links')), 
      '#weight' => 1,
    );

    $form['links']['#weight'] = 2;

    $register_link = variable_get('saml_create_new_account', '');
    $reset_pw_link = variable_get('saml_request_new_password', '');

    if (!empty($register_link)) {
      $form['links']['#markup'] =  str_replace(url('user/register', array('absolute' => FALSE)), $register_link, $form['links']['#markup']);
    }
    if (!empty($reset_pw_link)) {
      $form['links']['#markup'] =  str_replace(url('user/password', array('absolute' => FALSE)), $reset_pw_link, $form['links']['#markup']);
    }
  }
}