<?php

require_once 'consume.php';

/**
 *  * Implements hook_help.
 *   *
 *    * Displays help and module information.
 *     *
 *      * @param path 
 *       *   Which path of the site we're using to display help
 *        * @param arg 
 *         *   Array that holds the current path as returned from arg() function
 *          */
function onelogin_saml_help($path, $arg) {
   switch ($path) {
     case "admin/help#onelogin_saml":
       return '<p>'.  t("Allow signing into your Drupal site via OneLogin SAML technology") .'</p>';
       break;
   }
}

/**
 * Implements hook_menu()
 */
function onelogin_saml_menu(){
  $items = array();

  $items['admin/config/onelogin_saml_cert'] = array(
    'title' => 'Configure OneLogin SAML',
    'description' => 'Configuration of OneLogin SAML',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('onelogin_saml_cert_form'),
    'access arguments' => array('config saml'),
    'type' => MENU_NORMAL_ITEM
  );

  $items['onelogin_saml/consumer'] = array(
    'title' => 'SAML Consumer',
    'page callback' => 'onelogin_saml_consume',
    'access callback' => true,
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * * Configuration menu of x.509 Certificate for OneLogin SAML
 *  */
function onelogin_saml_cert_form() {

  $form = array();

  $form['onelogin_saml_cert'] = array(
    '#type' => 'textarea',
    '#title' => t('x.509 OneLogin certificate'),
    '#default_value' => variable_get('onelogin_saml_cert', ''),
    '#description' => t('Paste the x.509 certificate from OneLogin here'),
    '#required' => TRUE
  );
  $form['onelogin_saml_login_url'] = array(
    '#type' => 'textfield',
    '#title' => t('SAML Login URL'),
    '#default_value' => variable_get('onelogin_saml_login_url', ''),
    '#description' => t('You can find this url by editting your Drupal Application in OneLogin.'),
    '#required' => TRUE
  );

  return system_settings_form($form);
}

/**
 * * Implements hook_permission()
 *  */
function onelogin_saml_permission(){
  return array(
    'config saml' => array(
      'title' => t('Configure SAML Authentication'),
      'restricted' => true
    ),
    'saml consumer' => array(
      'title' => t('SAML Consumer'),
      'restricted' => false
    )
  );
}
